{$I MiMU\Integer.inc}
{$I MiMU\Double.inc}
{$I MiMU\String.inc}
{$I MiMU\Char.inc}
{$I MiMU\Boolean.inc}
{$I MiMU\TPoint.inc}
{$I MiMU\TBox.inc}
{$I MiMU\TRange.inc}
{$I MiMU\Int64.inc}
{$I MiMU\TIntegerArray.inc}
{$I MiMU\TDoubleArray.inc}
{$I MiMU\TStringArray.inc}
{$I MiMU\TCharArray.inc}
{$I MiMU\TBooleanArray.inc}
{$I MiMU\TPointArray.inc}
{$I MiMU\TBoxArray.inc}
{$I MiMU\TRangeArray.inc}
{$DEFINE Integer}
  {$I MiMU\Generic.inc}
  {$I MiMU\Sortable.inc}
{$UNDEF Integer}
{$DEFINE Double}
  {$I MiMU\Generic.inc}
  {$I MiMU\Sortable.inc}
{$UNDEF Double}
{$DEFINE string}
  {$I MiMU\Generic.inc}
  {$I MiMU\Sortable.inc}
{$UNDEF string}
{$DEFINE Char}
  {$I MiMU\Generic.inc}
  {$I MiMU\Sortable.inc}
{$UNDEF Char}
{$DEFINE Boolean}{$I MiMU\Generic.inc}{$UNDEF Boolean}
{$DEFINE TPoint}{$I MiMU\Generic.inc}{$UNDEF TPoint}
{$DEFINE TBox}{$I MiMU\Generic.inc}{$UNDEF TBox}
{$DEFINE TRange}{$I MiMU\Generic.inc}{$UNDEF TRange}

{$INCLUDE MiMU\config\Templates\D.inc}